### ISSUE TITLE
ForbiddenAttributesError

### ISSUE THREAD

**Issue by dfellows12** [learn-co-curriculum/displaying-associations-rails#15]
posts_controller.rb and categories_controller.rb are missing private strong params methods causing two tests to fail. 

  2) posts/edit shows an update form that submits content, redirects, and shows the updated content
     Failure/Error: post.update(params.require(:post))
     
     ActiveModel::ForbiddenAttributesError:
       ActiveModel::ForbiddenAttributesError

______________________________________________________

I was able to fix with the following : 

**posts_controller:**

	def update
		post = Post.find(params[:id])
		post.update(post_params)
		redirect_to post_path(post)
	end

	private

	def post_params
		params.require(:post).permit(:title, :description)
	end

**categories_controller.rb**

  def update
    category = Category.find(params[:id])
    category.update(category_params)
    redirect_to category_path(category)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

**Comment by sgharms** [comment]
Right you are! An important reminder that specs don't assure one a working app!
