### ISSUE TITLE
"data-visibility='hidden'" showing learn.co (also links to self)

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/displaying-associations-rails#2]
The link at the bottom of the page 

<img width="646" alt="screen shot 2016-01-16 at 1 52 19 pm" src="https://cloud.githubusercontent.com/assets/14326883/12372464/7899f448-bc58-11e5-9f6e-14a125eb314e.png">

```
<a href='https://learn.co/lessons/displaying-associations-rails'
data-visibility='hidden'>View this lesson on Learn.co</a>
```

I did some research, and it looks like 'data-visibility' is relaed to javascript, which I know nothing about. I didn't change it myself, because I don't want to mess-up something on the page. If "data-visibility='hidden'" can be deleted, I'll be happy to go and do that.

**Comment by onyoo** [comment]
Another related issue is that the link links to itself (as in the same page the link is found on)

**Comment by AnnJohn** [comment]
Thanks @onyoo. Have raised this issue with our product team.
