### ISSUE TITLE
Categories_controller_spec.rb -no category created

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/displaying-associations-rails#3]
When this lab is cloned from github and run, this is the error I got:

```
Failures:

  1) CategoriesController GET #show returns http success
     Failure/Error: @category = Category.find(params[:id])

     ActiveRecord::RecordNotFound:
       Couldn't find Category with 'id'=
     # ./app/controllers/categories_controller.rb:3:in `show'
     # ./spec/controllers/categories_controller_spec.rb:7:in `block (3 levels) in <top (required)>'

Finished in 0.07057 seconds (files took 1.44 seconds to load)
1 example, 1 failure
```

The spec calls `erb:'show'` with no id. I fixed the problem with a new instance of Category, and adding the id to the erb line, like this:

```
require 'rails_helper'

RSpec.describe CategoriesController, type: :controller do

  before do
    @category = Category.create!(name: "The Dangers of Stairs")
  end

  describe "GET #show" do
    it "returns http success" do
      get :show, id: @category
      expect(response).to have_http_status(:success)
    end
  end

end
```

I know we shouldn't edit the specs, but I couldn't find another way to pass the test. I've already spent over an hour getting to this point (there was no one on the ask a question line), so I figure raising an issue is the best solution.

**Comment by c1505** [comment]
After spending 45 minutes on ask, was told to do this as the solution.  I hope the lab is fixed so other people don't have to do the same thing.

**Comment by jmburges** [comment]
Thanks for the bug report @c1505 an @onyoo! Completely missed this one but it should be fixed now.
